language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install -y pdftk
install:
  - pip install -r requirement.txt
# command to run tests
script: 
  - python3 ./pdf-watermark.py -w 'File owner Ilya Khramtsov' -i Pie_aikataulu vko 25_2018.pdf
