language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirement.txt
  - pip install .
# command to run tests
script: 
  - python3 ./pdf-watermark.py -w 'File owner Ilya Khramtsov'
